### ISSUE TITLE
When debugging with LLDB, crash when loading PNG/JPEG using try Pixbuf.newFrom(file: "/user/username/Desktop/file.png")

### ISSUE THREAD

**Issue by austintatiousness** [rhx/SwiftGdkPixbuf#3]
I am certain it is probably an error in LLDB or whatever library loads PNGs/JPEGs, but on the off chance that it is not, I just wanted to report that when doing the following debugging with LLDB, a **Stop reason: signal SIGSEGV: invalid address (fault address: 0x1)** is raised. This error is not raised if the file does not exist. The call stack indicates it is happening in libjpeg or libpng

```
import SwiftGdkPixbuf
do {
    let i = try Pixbuf.newFrom(file: "/user/username/Desktop/file.png")
    //or
     let i2 = try Pixbuf(file: "/user/username/Desktop/file.png")
} catch {
    print(error)
}
```

This does not happen when running the built app. 
Ubuntu 20.04.2 LTS
GNOME: 3.36.8

**Comment by rhx** [comment]
Yes, I believe there is an LLDB bug under Linux that's causing these issues.  What version of Swift are you using?

**Comment by austintatiousness** [comment]
Swift version 5.3.3 (swift-5.3.3-RELEASE)

**Comment by rhx** [comment]
Does it make any difference if you try with the current Swift 5.4 development snapshot?

**Comment by rhx** [comment]
Appears to be an issue with Linux LLDB 5.3
